config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.twitter.api.stats:
      branch: main
      repo: https://github.com/cessda/cessda.twitter.api.stats
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.twitter.api.stats git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-firebrick-ant.sh
        container: qc.acc_pretty-seashell-tamarin
  QC.Doc:
    repos:
      github.com/cessda/cessda.twitter.api.stats find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ivory-horse.sh
        container: qc.doc_sunny-cardinal-grasshopper
      github.com/cessda/cessda.twitter.api.stats git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ivory-schnauzer.sh
        container: qc.doc_messy-sapphire-wasp
      github.com/cessda/cessda.twitter.api.stats markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-mustard-mandrill.sh
        container: qc.doc_tasty-silver-squid
  QC.Lic:
    repos:
      github.com/cessda/cessda.twitter.api.stats licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-denim-bongo.sh
        container: qc.lic_gloppy-copper-dolphin
  QC.Met:
    repos:
      github.com/cessda/cessda.twitter.api.stats cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-white-wolfhound.sh
        container: qc.met_beady-grey-terrier
  QC.Sec:
    repos:
      github.com/cessda/cessda.twitter.api.stats bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bronze-eagle.sh
        container: qc.sec_squirrely-flax-squirrel
  QC.Sty:
    repos:
      github.com/cessda/cessda.twitter.api.stats flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chocolate-shrimp.sh
        container: qc.sty_cheeky-xanthic-dolphin
  QC.Ver:
    repos:
      github.com/cessda/cessda.twitter.api.stats get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-gamboge-cat.sh
        container: qc.ver_cranky-buff-moth
timeout: 5400
